/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List targets */
        get: operations["listTargets"];
        put?: never;
        /** Create a target */
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Get a target */
        get: operations["getTarget"];
        put?: never;
        post?: never;
        /** Delete a target */
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List check configs */
        get: operations["listChecks"];
        put?: never;
        /** Create a check config */
        post: operations["createCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a check immediately */
        post: operations["runCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List results */
        get: operations["listResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Get a result */
        get: operations["getResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents */
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update incident state */
        patch: operations["patchIncident"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TargetType: "http" | "tcp" | "dns" | "tls";
        Target: {
            id?: string;
            name: string;
            type: components["schemas"]["TargetType"];
            address: string;
            tags?: string[];
            metadata?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        CheckType: "http" | "tcp" | "dns" | "tls";
        CheckConfig: {
            id?: string;
            type: components["schemas"]["CheckType"];
            target_id: string;
            /** @description Check interval in nanoseconds (time.Duration). */
            interval?: number;
            /** @description Check timeout in nanoseconds (time.Duration). */
            timeout?: number;
            params?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        CheckStatus: "ok" | "fail" | "timeout" | "unknown";
        Result: {
            id?: string;
            check_id?: string;
            target_id?: string;
            agent_id?: string;
            status?: components["schemas"]["CheckStatus"];
            /** @description Check duration in nanoseconds (time.Duration serialized as int64). */
            duration_ms?: number;
            error?: string;
            /** Format: date-time */
            timestamp?: string;
            metadata?: {
                [key: string]: string;
            };
            /** @description Snapshot of the target name at the time the check was executed. */
            target_name?: string;
        };
        /** @enum {string} */
        IncidentState: "open" | "acknowledged" | "resolved";
        Incident: {
            id?: string;
            target_id?: string;
            state?: components["schemas"]["IncidentState"];
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
            result_ids?: string[];
        };
        Error: {
            code?: string;
            message?: string;
        };
        TargetResponse: {
            data?: components["schemas"]["Target"];
            error?: components["schemas"]["Error"];
        };
        TargetListResponse: {
            data?: components["schemas"]["Target"][];
            error?: components["schemas"]["Error"];
        };
        CheckConfigResponse: {
            data?: components["schemas"]["CheckConfig"];
            error?: components["schemas"]["Error"];
        };
        CheckConfigListResponse: {
            data?: components["schemas"]["CheckConfig"][];
            error?: components["schemas"]["Error"];
        };
        ResultResponse: {
            data?: components["schemas"]["Result"];
            error?: components["schemas"]["Error"];
        };
        ResultListResponse: {
            data?: components["schemas"]["Result"][];
            error?: components["schemas"]["Error"];
        };
        IncidentResponse: {
            data?: components["schemas"]["Incident"];
            error?: components["schemas"]["Error"];
        };
        IncidentListResponse: {
            data?: components["schemas"]["Incident"][];
            error?: components["schemas"]["Error"];
        };
    };
    responses: {
        /** @description Invalid request body or parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TargetResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TargetResponse"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TargetResponse"];
            };
        };
    };
    parameters: {
        id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example 0.1.0 */
                        version?: string;
                    };
                };
            };
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Target"];
            };
        };
        responses: {
            /** @description Target created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listChecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of check configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckConfigListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckConfig"];
            };
        };
        responses: {
            /** @description Check config created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckConfigResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    runCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Check executed, result returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listResults: {
        parameters: {
            query?: {
                /** @description Filter by target ID */
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listIncidents: {
        parameters: {
            query?: {
                /** @description Filter by state. Omit to return all incidents. */
                state?: components["schemas"]["IncidentState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of incidents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    patchIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    state: components["schemas"]["IncidentState"];
                };
            };
        };
        responses: {
            /** @description Incident updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
