replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: ghcr.io/viniciushammett/gosre/gosre-notifier
  tag: "latest"
  pullPolicy: Always

env:
  natsURL: "nats://gosre-gosre-nats:4222"
  apiURL: "http://gosre-gosre-api:8080"
  redisAddr: "gosre-redis-master:6379"
  redisDB: "0"

apiKey: ""
redisPassword: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
