apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosre-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-api.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  database-url: {{ .Values.databaseURL | b64enc | quote }}
