replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: ghcr.io/viniciushammett/gosre/gosre-agent
  tag: "latest"
  pullPolicy: Always

env:
  apiURL: "http://gosre-api:8080"
  agentID: ""
  pollInterval: "30s"
  logLevel: "info"

apiKey: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
