apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gosre-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-exporter.labels" . | nindent 4 }}
data:
  GOSRE_API_URL: {{ .Values.env.apiURL | quote }}
  GOSRE_POLL_INTERVAL: {{ .Values.env.pollInterval | quote }}
  GOSRE_METRICS_PORT: {{ .Values.env.metricsPort | quote }}
