apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosre-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}
