apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gosre-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-scheduler.labels" . | nindent 4 }}
data:
  GOSRE_API_URL: {{ .Values.env.apiURL | quote }}
  NATS_URL: {{ .Values.env.natsURL | quote }}
  SCHEDULER_INTERVAL: {{ .Values.env.schedulerInterval | quote }}
