apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosre-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-scheduler.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}
  redis-url: {{ .Values.redisURL | b64enc | quote }}
