replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: ghcr.io/viniciushammett/gosre/gosre-web
  tag: "latest"
  pullPolicy: Always

env:
  apiURL: "http://gosre-api:8080"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
