apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gosre-notifier.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-notifier.labels" . | nindent 4 }}
data:
  GOSRE_NOTIFIER_NATS_URL: {{ .Values.env.natsURL | quote }}
  GOSRE_NOTIFIER_API_URL: {{ .Values.env.apiURL | quote }}
  GOSRE_NOTIFIER_REDIS_ADDR: {{ .Values.env.redisAddr | quote }}
  GOSRE_NOTIFIER_REDIS_DB: {{ .Values.env.redisDB | quote }}
