apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gosre-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-web.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.env.apiURL | quote }}
