apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gosre-catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-catalog.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.port | quote }}
