apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gosre-catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-catalog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gosre-catalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gosre-catalog.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gosre-catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gosre-catalog.fullname" . }}
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "gosre-catalog.fullname" . }}
                  key: database-url
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
