apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosre-catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-catalog.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.databaseURL | b64enc | quote }}
