version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - unused

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
