apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gosre-auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-auth.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  database-url: {{ .Values.databaseURL | b64enc | quote }}
  github-client-id: {{ .Values.githubClientID | b64enc | quote }}
  github-client-secret: {{ .Values.githubClientSecret | b64enc | quote }}
