replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: ghcr.io/viniciushammett/gosre/gosre-scheduler
  tag: "latest"
  pullPolicy: Always

env:
  apiURL: "http://gosre-gosre-api:8080"
  natsURL: "nats://gosre-gosre-nats:4222"
  schedulerInterval: "30s"

apiKey: ""
redisURL: "redis://gosre-redis-master:6379"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
