replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: ghcr.io/viniciushammett/gosre/gosre-api
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  dbPath: "/data/gosre.db"
  logLevel: "info"
  natsURL: ""
  catalogURL: "http://gosre-gosre-catalog:8081"

apiKey: ""
jwtSecret: ""
databaseURL: ""

persistence:
  enabled: true
  size: 1Gi
  storageClass: "managed-csi"
