apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gosre-nats.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-nats.labels" . | nindent 4 }}
data:
  nats.conf: |
{{ include "gosre-nats.config" . | trim | indent 4 }}
