apiVersion: v1
kind: Service
metadata:
  name: {{ include "gosre-nats.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-nats.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "gosre-nats.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      port: {{ .Values.service.clientPort }}
      targetPort: client
    - name: cluster
      port: {{ .Values.service.clusterPort }}
      targetPort: cluster
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gosre-nats.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gosre-nats.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "gosre-nats.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      port: {{ .Values.service.clientPort }}
      targetPort: client
    - name: monitor
      port: {{ .Values.service.monitorPort }}
      targetPort: monitor
